language: cpp

sudo: required

branches:
  only:
    - main

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - lcov
      before_script:
        - mkdir -p build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-5 -DBUILD_TESTS=ON -DENABLE_COVERAGE=ON -DGEN_DOCS=OFF ..
      script:
        - cmake build .
        - cmake build . --target coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
      env:
        - MATRIX_EVAL="COMPILER=g++-5 && BUILD_TYPE=Release"
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env:
        - MATRIX_EVAL="COMPILER=clang++ && BUILD_TYPE=Debug"
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env:
        - MATRIX_EVAL="COMPILER=clang++ && BUILD_TYPE=Release"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=$COMPILER -DBUILD_TESTS=ON -DGEN_DOCS=OFF ..

script:
  - cmake --build . -- -j2
  - ctest --output-on-failure
