language: cpp

sudo: required

branches:
  only:
    - main

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - lcov
      cache:
        apt: true
      before_script:
        - mkdir -p build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-5 -DBUILD_TESTS=ON -DENABLE_COVERAGE=ON -DGEN_DOCS=OFF ..
      script:
        - make -j2
        - ctest --output-on-failure
        - make coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
      cache:
        apt: true
      env:
        - MATRIX_EVAL="COMPILER=g++-5 && BUILD_TYPE=Release"
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - doxygen
            - sphinx-doc
            - python3-pip
            - python3-setuptools
      before_install:
        - pip3 install sphinx
        - pip3 install sphinx-rtd-theme
        - pip3 install breathe
        - pip3 install sphinx-sitemap
      cache:
        apt: true
      before_script:
        - mkdir -p build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-5 -DBUILD_TESTS=OFF -DENABLE_COVERAGE=OFF -DGEN_DOCS=ON ..
      script:
        - cd ../docs/sphinx
        - make html
        - cd _build/html
        - touch .nojekyll
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        target_branch: gh-pages
        on:
          branch: main
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env:
        - MATRIX_EVAL="COMPILER=clang++ && BUILD_TYPE=Debug"
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env:
        - MATRIX_EVAL="COMPILER=clang++ && BUILD_TYPE=Release"

cache:
  apt: true

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=$COMPILER -DBUILD_TESTS=ON -DGEN_DOCS=OFF ..

script:
  - make -j2
  - ctest --output-on-failure
